### PR TITLE
Update for Linux 6.2

### PR DESCRIPTION
**Pull request by rnestler**

### CODE REVIEW

**Comment by ojeda** [comment]
Thanks!

**Comment by ojeda** [comment]
By the way, for this repository does not matter much because it most likely not go into the kernel, but it would still be nice if you could sign your commits with `Signed-off-by` to simplify things! Please see the DCO https://www.kernel.org/doc/html/latest/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

**Comment by ojeda** [comment]
Thanks for signing it!

**Comment by rnestler** [comment]
> Thanks for signing it!

I did a `git commit --amend -s` which added the signed-off-by tag. Didn't know this was possible until I read the link you posted above :slightly_smiling_face:

**Comment by ojeda** [comment]
Yeah, apart from the DCO implications, it is also useful for projects where multiple people may handle/review/test/etc. patches and want to keep all that within the commit message :)

**Pull request merged**
